apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend-01
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: java-backend-01
          image: quyentqghtk/java-backend-01:v1.0.2
          ports:
            - containerPort: 8081
